apiVersion: v1
entries:
  personal-site:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-02-15T08:51:25.9996062+01:00"
    description: Personal site
    digest: 97a0cd021db5a8d3edbb33a6535e6b4ed1d2700e9b9e0ce8d37642b595d778f5
    name: personal-site
    type: application
    urls:
    - personal-site-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2026-02-15T08:51:25.999087+01:00"
    description: Personal site
    digest: a3707eea7c287bf96bc3ddfc654f31312226660a5f62a293294ca221cce67491
    name: personal-site
    type: application
    urls:
    - personal-site-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2026-02-15T08:51:25.996315+01:00"
    description: Personal site
    digest: 2340eecf7fa601493ec2b368711d7ab3454634c4e682e03c318f5c58621db7db
    name: personal-site
    type: application
    urls:
    - personal-site-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2026-02-15T08:51:25.9839232+01:00"
    description: Personal site
    digest: 262ba70f4966685fbcae2d0343211ed196adee7a533a83b761868cca7f6c114e
    name: personal-site
    type: application
    urls:
    - personal-site-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2026-02-15T08:51:25.9686197+01:00"
    description: Personal site
    digest: d6a6f59c2cee1f7161c64019d9986ee8cdd2bf029f7ec762b639a99f2af4e04a
    name: personal-site
    type: application
    urls:
    - personal-site-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2026-02-15T08:51:25.9565783+01:00"
    description: Personal site
    digest: e869935b6c5818abc534d1d3b0782548fd2397271c3f1186485046d3296b1386
    name: personal-site
    type: application
    urls:
    - personal-site-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2026-02-15T08:51:25.9434273+01:00"
    description: Personal site
    digest: f166c67d842cf74fc1468b1af27d7a30dfa33989c325458d74cf7ded4d7e341d
    name: personal-site
    type: application
    urls:
    - personal-site-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-15T08:51:25.927989+01:00"
    description: Personal site
    digest: d86f9253f9646d79177b847be627e9dedbc172bbf46465e6ca942f347070f119
    name: personal-site
    type: application
    urls:
    - personal-site-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-15T08:51:25.9080322+01:00"
